version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-reverse
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
